#!/bin/bash
# setup.sh — Interactive setup for hermes-self-backup.
# Generates hermes-backup.sh and hermes-restore.sh in ~/.hermes/scripts/
# after gathering GitHub repo details and user preferences.
set -euo pipefail

HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
REPO_FILE="$HERMES_HOME/.backup-repo"

# Colours
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}=== Hermes Self-Backup Setup ===${NC}"
echo ""

# ------------------------------------------------------------------
# 1. Verify prerequisites
# ------------------------------------------------------------------

if ! command -v gh &>/dev/null; then
    echo -e "${RED}ERROR: GitHub CLI (gh) is required.${NC}"
    echo "Install it: https://cli.github.com/"
    exit 1
fi

if ! command -v git &>/dev/null; then
    echo -e "${RED}ERROR: git is required.${NC}"
    exit 1
fi

GH_USER=$(gh api user -q '.login' 2>/dev/null) || {
    echo -e "${RED}ERROR: Not authenticated with gh.${NC} Run: gh auth login"
    exit 1
}

echo -e "${GREEN}✓ GitHub user: $GH_USER${NC}"
echo ""

# ------------------------------------------------------------------
# 2. Determine GitHub repo
# ------------------------------------------------------------------

if [ -f "$REPO_FILE" ]; then
    EXISTING=$(cat "$REPO_FILE")
    echo -e "Existing backup repo found: ${EXISTING}"
    read -rp "Use this repo? [Y/n]: " reuse
    if [[ "$reuse" =~ ^[Nn]$ ]]; then
        REPO=""
    else
        REPO="$EXISTING"
    fi
else
    REPO=""
fi

if [ -z "$REPO" ]; then
    DEFAULT_NAME="hermes-state-backup"
    echo "Choose a name for your private backup repository."
    echo "This MUST be different from 'hermes-self-backup'."
    read -rp "Repo name [$DEFAULT_NAME]: " input_name
    NAME="${input_name:-$DEFAULT_NAME}"

    # Validate: must not be hermes-self-backup
    if [ "${NAME}" = "hermes-self-backup" ]; then
        echo -e "${RED}ERROR: 'hermes-self-backup' is reserved. Please choose a different name.${NC}"
        exit 1
    fi

    # Ensure user/repo format
    if [[ "$NAME" =~ / ]]; then
        REPO="$NAME"
    else
        REPO="${GH_USER}/${NAME}"
    fi

    # Create if it doesn't exist
    if ! gh repo view "$REPO" &>/dev/null; then
        echo "Creating private repo $REPO ..."
        gh repo create "$REPO" --private --description "Hermes Agent self-backup" || {
            echo -e "${RED}Failed to create repo.${NC}"
            exit 1
        }
    fi

    echo "$REPO" > "$REPO_FILE"
fi

echo -e "${GREEN}✓ Backup repo: https://github.com/$REPO${NC}"
echo ""

# ------------------------------------------------------------------
# 3. GPG check for encrypted secret backup
# ------------------------------------------------------------------

GPG_AVAILABLE=false
if command -v gpg &>/dev/null; then
    GPG_AVAILABLE=true
    echo -e "${GREEN}✓ gpg available for optional encrypted secret backup${NC}"
else
    echo -e "${YELLOW}⚠ gpg not found. Encrypted secret backup will be unavailable.${NC}"
fi
echo ""

# ------------------------------------------------------------------
# 4. Generate scripts
# ------------------------------------------------------------------

SCRIPT_DIR="$HERMES_HOME/scripts"
mkdir -p "$SCRIPT_DIR"

GEN_DATE=$(date -Iseconds)

# --- hermes-backup.sh ---
cat > "$SCRIPT_DIR/hermes-backup.sh" <<'BACKUP_EOF'
#!/bin/bash
# Generated by hermes-self-backup setup.sh on GEN_DATE
# Pushes Hermes state to GitHub.
set -euo pipefail

HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
BACKUP_DIR="${HERMES_HOME}/.backup-staging"
LOG_FILE="${HERMES_HOME}/logs/self-backup.log"
REPO_FILE="${HERMES_HOME}/.backup-repo"

mkdir -p "$(dirname "$LOG_FILE")"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

# Colours
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

if ! command -v gh &>/dev/null; then
    echo -e "${RED}ERROR: gh CLI required.${NC}"
    exit 1
fi

REPO=""
[ -f "$REPO_FILE" ] && REPO=$(cat "$REPO_FILE")
if [ -z "$REPO" ]; then
    echo -e "${RED}ERROR: No backup repo configured. Run setup first.${NC}"
    exit 1
fi

# Staging
rm -rf "$BACKUP_DIR"
mkdir -p "$BACKUP_DIR"
cd "$BACKUP_DIR"
git init -q
git remote add origin "https://github.com/${REPO}.git" 2>/dev/null || \
    git remote set-url origin "https://github.com/${REPO}.git"

# Iron-clad .gitignore
cat > "$BACKUP_DIR/.gitignore" <<'GIN'
# Secrets
.env?
*.key
*.pem
*.pfx
*.p12
*.crt
auth.json
*token*
*secret*
*password*
*.gpg
*.age

# Runtime
__pycache__/
*.pyc
*.pyo
*.log
node_modules/
.venv/
venv/

# Large / reinstallable
hermes-agent/
sessions/
logs/
openclaw-imports/

# OS detritus
.DS_Store
Thumbs.db
*.swp
*~
GIN
git add .gitignore

# Manifest
HERMES_VER=$(hermes --version 2>/dev/null | head -1 || echo "unknown")
HOST=$(hostname)
DATE=$(date -Iseconds)
cat > "$BACKUP_DIR/manifest.json" <<EOF
{
  "version": "2.0",
  "backup_date": "$DATE",
  "hostname": "$HOST",
  "hermes_version": "$HERMES_VER",
  "repo": "$REPO",
  "backed_up_by": "hermes-self-backup"
}
EOF
git add manifest.json

# Backup items
echo ""
echo -e "${YELLOW}=== Backing up ===${NC}"

if [ -d "$HERMES_HOME/skills" ]; then
    echo "  + skills/"
    mkdir -p "$BACKUP_DIR/skills"
    find "$HERMES_HOME/skills" -mindepth 1 -maxdepth 1 -type d | while read -r d; do
        cp -a "$d" "$BACKUP_DIR/skills/$(basename "$d")" 2>/dev/null || true
    done
    git add skills/ 2>/dev/null || true
fi

if [ -f "$HERMES_HOME/config.yaml" ]; then
    echo "  + config.yaml"
    cp "$HERMES_HOME/config.yaml" "$BACKUP_DIR/"
    git add config.yaml
fi

if [ -d "$HERMES_HOME/profiles" ]; then
    echo "  + profiles/"
    mkdir -p "$BACKUP_DIR/profiles"
    for pdir in "$HERMES_HOME/profiles"/*; do
        [ -d "$pdir" ] || continue
        pname=$(basename "$pdir")
        mkdir -p "$BACKUP_DIR/profiles/$pname"
        [ -f "$pdir/config.yaml" ] && cp "$pdir/config.yaml" "$BACKUP_DIR/profiles/$pname/"
        if [ -d "$pdir/skills" ]; then
            mkdir -p "$BACKUP_DIR/profiles/$pname/skills"
            find "$pdir/skills" -mindepth 1 -maxdepth 1 -type d | while read -r d; do
                cp -a "$d" "$BACKUP_DIR/profiles/$pname/skills/$(basename "$d")" 2>/dev/null || true
            done
        fi
    done
    git add profiles/ 2>/dev/null || true
fi

if [ -d "$HERMES_HOME/cron" ]; then
    echo "  + cron/"
    mkdir -p "$BACKUP_DIR/cron"
    find "$HERMES_HOME/cron" -maxdepth 2 -type f \( -name "*.yaml" -o -name "*.yml" -o -name "*.json" \) -exec cp {} "$BACKUP_DIR/cron/" \; 2>/dev/null || true
    git add cron/ 2>/dev/null || true
fi

if [ -d "$HERMES_HOME/scripts" ]; then
    echo "  + scripts/"
    mkdir -p "$BACKUP_DIR/scripts"
    for s in "$HERMES_HOME/scripts"/hermes-*.sh; do
        [ -f "$s" ] || continue
        cp "$s" "$BACKUP_DIR/scripts/" 2>/dev/null || true
    done
    git add scripts/ 2>/dev/null || true
fi

if [ -f "$HERMES_HOME/.persona.md" ]; then
    echo "  + .persona.md"
    cp "$HERMES_HOME/.persona.md" "$BACKUP_DIR/"
    git add .persona.md
fi

# Optional encrypted secret backup
echo ""
if command -v gpg &>/dev/null; then
    read -rp "Encrypt and backup local secret files? (requires gpg passphrase) [y/N]: " enc
    if [[ "$enc" =~ ^[Yy]$ ]]; then
        SECRET_FILE="$HERMES_HOME/.env"
        if [ -f "$SECRET_FILE" ]; then
            echo "  + Encrypting main secrets"
            gpg --symmetric --cipher-algo AES256 --compress-algo 1 \
                --output "$BACKUP_DIR/secrets.gpg" "$SECRET_FILE"
            git add secrets.gpg
        fi
        for penv in "$HERMES_HOME/profiles"/*/.env; do
            [ -f "$penv" ] || continue
            pname=$(basename "$(dirname "$penv")")
            mkdir -p "$BACKUP_DIR/profiles/$pname"
            echo "  + Encrypting profiles/$pname secrets"
            gpg --symmetric --cipher-algo AES256 --compress-algo 1 \
                --output "$BACKUP_DIR/profiles/$pname/secrets.gpg" "$penv"
            git add "profiles/$pname/secrets.gpg"
        done
        echo -e "${GREEN}Encrypted secret files added.${NC}"
    else
        echo -e "${YELLOW}Skipping secret backup. After restore you must re-enter credentials.${NC}"
    fi
else
    echo -e "${YELLOW}gpg not available. Skipping secret encryption.${NC}"
fi

# Commit & push
echo ""
echo -e "${YELLOW}Pushing to $REPO ...${NC}"
git add -A 2>/dev/null || true
git commit -m "backup: ${DATE}" --quiet || {
    echo -e "${GREEN}No changes.${NC}"
    exit 0
}
git branch -M main
if ! git push -u origin main 2>/dev/null; then
    TOKEN=$(gh auth token 2>/dev/null) || true
    if [ -n "${TOKEN:-}" ]; then
        git remote set-url origin "https://x-access-token:${TOKEN}@github.com/${REPO}.git"
        git push -u origin main
    else
        echo -e "${RED}Push failed. Check gh auth.${NC}"
        exit 1
    fi
fi

echo ""
echo -e "${GREEN}Backup complete: https://github.com/$REPO${NC}"
log "Backup pushed to $REPO"
BACKUP_EOF

# --- hermes-restore.sh ---
cat > "$SCRIPT_DIR/hermes-restore.sh" <<'RESTORE_EOF'
#!/bin/bash
# Generated by hermes-self-backup setup.sh on GEN_DATE
# Restores Hermes state from GitHub.
set -euo pipefail

HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
RESTORE_DIR="${HERMES_HOME}/.backup-staging"
LOG_FILE="${HERMES_HOME}/logs/self-backup.log"
REPO_FILE="${HERMES_HOME}/.backup-repo"

mkdir -p "$(dirname "$LOG_FILE")"
log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"; }

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

if ! command -v git &>/dev/null; then
    echo -e "${RED}ERROR: git required.${NC}"; exit 1
fi
if ! command -v gh &>/dev/null; then
    echo -e "${RED}ERROR: gh required.${NC}"; exit 1
fi

REPO=""
[ -f "$REPO_FILE" ] && REPO=$(cat "$REPO_FILE")
if [ -z "$REPO" ]; then
    read -rp "Backup repo (e.g. user/repo): " REPO
    echo "$REPO" > "$REPO_FILE"
fi

echo -e "${YELLOW}Cloning backup ...${NC}"
rm -rf "$RESTORE_DIR"
gh repo clone "$REPO" "$RESTORE_DIR" -- -q || {
    echo -e "${RED}Clone failed.${NC}"; exit 1
}

MANIFEST_DATE=$(cat "$RESTORE_DIR/manifest.json" 2>/dev/null | grep -oP '"backup_date":\s*"\K[^"]+' || echo "unknown")
echo -e "${BLUE}Backup date: $MANIFEST_DATE${NC}"
echo ""

# Restore helpers
restore_file() {
    local src="$1" dst="$2"
    [ -f "$src" ] || return 0
    if [ -f "$dst" ]; then
        read -rp "Overwrite $dst? [y/N]: " yn
        [[ "$yn" =~ ^[Yy]$ ]] || return 0
    fi
    cp "$src" "$dst"
    echo -e "  ${GREEN}+ $dst${NC}"
}

restore_dir() {
    local src="$1" dst="$2"
    [ -d "$src" ] || return 0
    mkdir -p "$dst"
    find "$src" -type f | while read -r f; do
        rel="${f#$src/}"
        target="$dst/$rel"
        if [ -f "$target" ]; then
            if diff -q "$f" "$target" >/dev/null 2>&1; then continue; fi
            echo "Conflict: $target"
            read -rp "  Overwrite? [y/N/d]: " yn
            case "$yn" in
                [Yy]*) cp "$f" "$target"; echo -e "  ${GREEN}+ overwritten${NC}" ;;
                [Dd]*) diff -u "$target" "$f" | head -40 ;;
                *) echo -e "  ${YELLOW}- skipped${NC}" ;;
            esac
        else
            mkdir -p "$(dirname "$target")"
            cp "$f" "$target"
            echo -e "  ${GREEN}+ $rel${NC}"
        fi
    done
}

echo -e "${YELLOW}=== Restoring ===${NC}"

restore_file "$RESTORE_DIR/config.yaml" "$HERMES_HOME/config.yaml"

if [ -d "$RESTORE_DIR/skills" ]; then
    echo "Restoring skills..."
    restore_dir "$RESTORE_DIR/skills" "$HERMES_HOME/skills"
fi

if [ -d "$RESTORE_DIR/profiles" ]; then
    echo "Restoring profiles..."
    for pdir in "$RESTORE_DIR/profiles"/*; do
        [ -d "$pdir" ] || continue
        pname=$(basename "$pdir")
        mkdir -p "$HERMES_HOME/profiles/$pname"
        restore_file "$pdir/config.yaml" "$HERMES_HOME/profiles/$pname/config.yaml"
        if [ -d "$pdir/skills" ]; then
            restore_dir "$pdir/skills" "$HERMES_HOME/profiles/$pname/skills"
        fi
    done
fi

if [ -d "$RESTORE_DIR/cron" ]; then
    echo "Restoring cron..."
    mkdir -p "$HERMES_HOME/cron"
    find "$RESTORE_DIR/cron" -maxdepth 1 -type f -exec cp {} "$HERMES_HOME/cron/" \;
fi

if [ -d "$RESTORE_DIR/scripts" ]; then
    echo "Restoring scripts..."
    mkdir -p "$HERMES_HOME/scripts"
    find "$RESTORE_DIR/scripts" -maxdepth 1 -type f -exec cp {} "$HERMES_HOME/scripts/" \;
fi

restore_file "$RESTORE_DIR/.persona.md" "$HERMES_HOME/.persona.md"

# Encrypted secrets
echo ""
if [ -f "$RESTORE_DIR/secrets.gpg" ]; then
    echo -e "${YELLOW}Encrypted secrets found.${NC}"
    SECRET_TARGET="$HERMES_HOME/.env"
    if [ -f "$SECRET_TARGET" ]; then
        echo -e "${YELLOW}Warning: $SECRET_TARGET already exists.${NC}"
        read -rp "  Decrypt and overwrite? [y/N]: " yn
        [[ "$yn" =~ ^[Yy]$ ]] || { echo "  Skipped. Decrypt manually: gpg -d $RESTORE_DIR/secrets.gpg > $SECRET_TARGET"; }
    else
        read -rp "  Decrypt secrets to $SECRET_TARGET? [Y/n]: " yn
        if [[ ! "$yn" =~ ^[Nn]$ ]]; then
            gpg -d "$RESTORE_DIR/secrets.gpg" > "$SECRET_TARGET"
            echo -e "  ${GREEN}+ Decrypted${NC}"
        fi
    fi
else
    echo -e "${YELLOW}No encrypted secrets in backup. Re-enter credentials in your local secrets file after restore.${NC}"
fi

for pgpg in "$RESTORE_DIR/profiles"/*/secrets.gpg; do
    [ -f "$pgpg" ] || continue
    pname=$(basename "$(dirname "$pgpg")")
    target="$HERMES_HOME/profiles/$pname/.env"
    echo ""
    if [ -f "$target" ]; then
        read -rp "Decrypt profiles/$pname secrets and overwrite? [y/N]: " yn
        [[ "$yn" =~ ^[Yy]$ ]] || { echo "  Skipped."; continue; }
    fi
    mkdir -p "$(dirname "$target")"
    gpg -d "$pgpg" > "$target"
    echo -e "  ${GREEN}+ Decrypted profiles/$pname/.env${NC}"
done

echo ""
echo -e "${GREEN}Restore complete!${NC}"
echo ""
echo "Next steps:"
echo "  1. hermes config check"
echo "  2. hermes skills list"
echo "  3. hermes cron list"
echo "  4. If secrets were not restored, re-enter credentials in your local secrets file"
echo "  5. hermes doctor"
echo ""
log "Restored from $REPO (backup date: $MANIFEST_DATE)"
RESTORE_EOF

# Substitute GEN_DATE
cd "$SCRIPT_DIR"
sed -i "s/GEN_DATE/$GEN_DATE/g" hermes-backup.sh hermes-restore.sh

chmod +x hermes-backup.sh hermes-restore.sh

echo ""
echo -e "${GREEN}✓ Scripts generated:${NC}"
echo "  $SCRIPT_DIR/hermes-backup.sh"
echo "  $SCRIPT_DIR/hermes-restore.sh"
echo ""
echo "Next steps:"
echo "  ~/.hermes/scripts/hermes-backup.sh     # back up now"
echo "  ~/.hermes/scripts/hermes-restore.sh    # restore later"
